# Generated by Django 4.0 on 2022-08-21 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0002_category_characters_cat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('id',), 'verbose_name': 'Категории', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='characters',
            options={'ordering': ('-time_create', 'title'), 'verbose_name': 'Персонажи', 'verbose_name_plural': 'Персонажи'},
        ),
        migrations.AddField(
            model_name='characters',
            name='slug',
            field=models.SlugField(max_length=255, null=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='characters',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Заголовок'),
        ),
    ]
