# Generated by Django 4.0 on 2022-08-22 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0003_alter_category_options_alter_characters_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characters',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='URL'),
        ),
    ]
