# Generated by Django 4.0 on 2022-08-22 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0005_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='URL'),
        ),
    ]
