"""empty message

Revision ID: 4feac3a50b8f
Revises: 7e8c9b38d8d8
Create Date: 2024-10-07 20:09:37.877029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4feac3a50b8f'
down_revision: Union[str, None] = '7e8c9b38d8d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq__character__id'), 'character', ['id'])
    op.create_unique_constraint(op.f('uq__character__name'), 'character', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq__character__name'), 'character', type_='unique')
    op.drop_constraint(op.f('uq__character__id'), 'character', type_='unique')
    # ### end Alembic commands ###
